# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-13 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20170613_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='map',
            name='image',
            field=models.ImageField(default=1, height_field='height', upload_to='', width_field='width'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
