# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-13 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20170613_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='image',
            field=models.ImageField(default='', height_field='height', upload_to=b'', width_field='width'),
            preserve_default=False,
        ),
    ]
