# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-13 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20170613_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='image',
            field=models.ImageField(height_field='height', upload_to='', width_field='width'),
        ),
    ]
