# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-13 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20170613_1106'),
        ('map', '0005_auto_20170613_1351'),
    ]

    operations = [
    ]
